/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package form.pricelist;

import controller.ClientController;
import domain.PriceList;
import domain.PriceListItem;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import models.TableModelStavkaCenovnika;
import models.TableModelStavkaCenovnikaIzmena;

/**
 *
 * @author Petar
 */
public class IzmeniCenovnikForm extends javax.swing.JDialog {

    PriceList cenovnik;

    /**
     * Creates new form IzmeniCenovnikForm
     */
    public IzmeniCenovnikForm(IzmenaCenovnikaForm parent, boolean modal, PriceList priceList) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        cenovnik = priceList;
        jTabelaStavki.setModel(new TableModelStavkaCenovnikaIzmena(cenovnik));
        SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");
        jFormattedDatumOd.setText(String.valueOf(sdf.format(priceList.getValidFrom())));
        jFormattedDatumDo.setText(String.valueOf(sdf.format(priceList.getValidTo())));

//        popuniTabelu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jFormattedDatumOd = new javax.swing.JFormattedTextField();
        jFormattedDatumDo = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabelaStavki = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Izmena cenovnika");

        jLabel1.setText("Datum od (dd.MM.yyyy):");

        jFormattedDatumOd.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd.MM.yyyy"))));

        jFormattedDatumDo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd.MM.yyyy"))));

        jLabel2.setText("Datum do (dd.MM.yyyy):");

        jButton1.setText("Izmeni stavku");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTabelaStavki.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTabelaStavki);

        jButton2.setText("Izmeni cenovnik");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jFormattedDatumOd))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jFormattedDatumDo, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jFormattedDatumOd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jFormattedDatumDo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here: 
        int row = jTabelaStavki.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Odaberite red!");
            return;
        }

        TableModelStavkaCenovnikaIzmena mt = (TableModelStavkaCenovnikaIzmena) jTabelaStavki.getModel();
        PriceListItem stavka = mt.vratiStavku(row);
        PodaciStavkeForm forma = new PodaciStavkeForm(this, true, stavka);
        forma.setVisible(true);
        jTabelaStavki.setModel(new TableModelStavkaCenovnikaIzmena(cenovnik));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            // TODO add your handling code here:
            if (jFormattedDatumDo.getText().isEmpty() || jFormattedDatumOd.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Popunite datume");
                return;
            }

            SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");
            Date datumOd = sdf.parse(jFormattedDatumOd.getText());
            Date datumDo = sdf.parse(jFormattedDatumDo.getText());

            if (datumOd.after(datumDo)) {
                JOptionPane.showMessageDialog(this, "Datum od mora biti pre Datum do");
                return;
            }
            cenovnik.setValidFrom(datumOd);
            cenovnik.setValidTo(datumDo);

            try {
                ClientController.getInstance().updatePriceList(cenovnik);
                JOptionPane.showMessageDialog(this, "Uspesno azuriran cenovnik");
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
//                Logger.getLogger(IzmeniCenovnikForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
//            Logger.getLogger(IzmeniCenovnikForm.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JFormattedTextField jFormattedDatumDo;
    private javax.swing.JFormattedTextField jFormattedDatumOd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTabelaStavki;
    // End of variables declaration//GEN-END:variables

    private void popuniTabelu() {
        TableModelStavkaCenovnikaIzmena mt = (TableModelStavkaCenovnikaIzmena) jTabelaStavki.getModel();
        ArrayList<PriceListItem> stavke = cenovnik.getPriceListItems();
        System.out.println(cenovnik.getPriceListID());
//        mt.ubaciListu(cenovnik.getPriceListItems());

    }
}
